CREATE TABLE transactions (
	'ID' int(11) NOT NULL AUTO_INCREMENT,
	'receipt_id' varchar(200) NOT NULL, 
	'txn_id' varchar(200) NOT NULL,
	'parent_txn_id' varchar(20) NOT NULL, 
	'payment_date' date DEFAULT NOT NULL, 
	'payment_currency' varchar(127) NOT NULL,
	'verify_sign' varchar(200) NOT NULL,
	'first_name' varchar(64) DEFAULT NOT NULL, 
	'last_name' varchar(64) DEFAULT NOT NULL, 
	'payer_status' varchar(200) NOT NULL,
	'payer_id' varchar(13) NOT NULL, 
	'payer_email' varchar(127) DEFAULT NOT NULL, 
	'contact_phone' varchar(20) NOT NULL,
	'address_street' varchar(200) NOT NULL,
	'address_city' varchar(40) NOT NULL,
	'address_zip' varchar(20) NOT NULL,
	'address_country' varchar(64) NOT NULL,
	'address_status' varchar(15) NOT NULL,
	'prod_id_array' MEDIUMTEXT NOT NULL,
	'num_cart_items' TINYINT NOT NULL,
	'payment_status' varchar(64) NOT NULL,
	'pending_reason' varchar(128) NULL,
	'payment_type' varchar(64) NOT NULL,
	'mc_currency' varchar(128),
	'mc_gross' FLOAT NOT NULL,
	'mc_fee' FLOAT NOT NULL,
	'receiver_email' varchar(127) NOT NULL
    PRIMARY KEY ('ID')
    );